baseURL = "https://aburchardt.dk/kea/3_semester/aeroe/"
languageCode = "en-us"
title = "Opgave 2"
theme = "aeroe"
publishDir = "docs"
Paginate = 3

[[menu.main]]
name               	= "Hjem"
weight             	= -201
identifier         	= "hjem"
url                	= "/"

[[menu.main]]
name               	= "Dokumentation"
weight             	= -103
identifier         	= "dokumentation"
url                	= "/dokumentation/"

[[menu.main]]
name               	= "Om"
weight             	= -100
identifier         	= "om"
url                	= "/om/"

[[menu.main]]
name               	= "Datavisualisering"
weight             	= -102
identifier         	= "datavisualisering"
url                	= "/datavisualisering/"

[params]
description = "test test config"
recent_posts_number = 2
